spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aws-0-ap-northeast-2.pooler.supabase.com
    username: postgres.rkaeclmrxuybbidxfwhq
    password: ShoppingMallList
    driver-class-name: org.postgresql.Driver