#spring:
#  datasource:
#    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
#    username: postgres.rkaeclmrxuybbidxfwhq

jpa:
  properties:
    hibernate:
      show_sql: true
      format_sql: true
      highlight_sql: true

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
server:
  port: 8092
